"""Fixture-based tests for parse_detail_sections.

Each test loads a sanitized timelineDetailV2 response captured from a real
TR account, runs the parser, and asserts the structured fields the parser
should extract.

The fixtures live in tests/fixtures/ and were generated by
scripts/extract_fixture.py. When TR changes the JSON shape, these tests
will fail loudly with a clear diff between expected and actual values.
"""

import json
from pathlib import Path

import pytest

from traderepublic_sync import parse_detail_sections

FIXTURES = Path(__file__).parent / "fixtures"


def load_raw(name: str) -> dict:
    """Return the _detail_raw payload (the timelineDetailV2 response)."""
    item = json.loads((FIXTURES / f"{name}.json").read_text())
    return item["_detail_raw"]


def test_purchase_savingsplan():
    parsed = parse_detail_sections(load_raw("purchase_savingsplan"))
    assert parsed["asset_name"] == "Edge MSCI EM Value USD (Acc)"
    assert parsed["quantity"] == pytest.approx(0.305922)
    assert parsed["unit_price"] == pytest.approx(81.72)
    assert parsed["total"] == pytest.approx(25.0)
    assert parsed["fees"] is None  # "Gratuit" — not parseable as a number
    assert parsed["event_description"].startswith("Vous avez épargné")
    assert len(parsed["document_urls"]) == 1


def test_trade_with_fees_and_taxes():
    parsed = parse_detail_sections(load_raw("trade"))
    assert parsed["isin"] == "FR0000052292"  # extracted from header action.payload
    assert parsed["asset_name"] == "Hermes"
    assert parsed["portfolio"] == "PEA"
    assert parsed["quantity"] == pytest.approx(1.0)
    assert parsed["unit_price"] == pytest.approx(1596.0)
    assert parsed["total"] == pytest.approx(1603.38)
    assert parsed["fees"] == pytest.approx(1.0)
    assert parsed["fees_currency"] == "EUR"
    assert parsed["taxes"] == pytest.approx(6.38)
    assert parsed["taxes_currency"] == "EUR"


def test_dividend():
    parsed = parse_detail_sections(load_raw("dividend"))
    assert parsed["asset_name"] == "Air Liquide"
    assert parsed["order_type"] == "Dividende en espèces"
    assert parsed["quantity"] == pytest.approx(2.0)
    assert parsed["dividend_per_share"] == pytest.approx(3.7)
    assert parsed["dividend_currency"] == "EUR"
    assert parsed["total"] == pytest.approx(7.4)
    # 0,00 € taxes — taxes field is set, but to 0
    assert parsed["taxes"] == pytest.approx(0.0)


def test_interest():
    parsed = parse_detail_sections(load_raw("interest"))
    assert parsed["total"] == pytest.approx(0.62)
    # Interest payouts can have withholding tax
    assert parsed["taxes"] == pytest.approx(0.29)
    assert parsed["taxes_currency"] == "EUR"
    assert parsed["asset_name"] is None  # no underlying asset
    assert parsed["event_description"].startswith("Vous avez reçu")


def test_transfer_in():
    parsed = parse_detail_sections(load_raw("transfer_in"))
    assert parsed["total"] == pytest.approx(200.0)
    assert parsed["sender"] == "M JOHN DOE"
    assert parsed["iban"] == "..0000"  # TR redacts to last 4 chars
    assert parsed["asset_name"] is None
    assert parsed["isin"] is None


def test_card_expense():
    parsed = parse_detail_sections(load_raw("card_expense"))
    assert parsed["total"] == pytest.approx(4.9)
    assert parsed["event_description"].startswith("Vous avez dépensé")
    assert parsed["asset_name"] is None  # card spend, no asset
    assert parsed["isin"] is None


@pytest.mark.parametrize("name", [
    "purchase_savingsplan", "trade", "dividend",
    "interest", "transfer_in", "card_expense",
])
def test_parser_never_crashes(name):
    """Every fixture must parse without raising — defensive coverage."""
    result = parse_detail_sections(load_raw(name))
    # Result must always be a dict with the expected keys
    assert isinstance(result, dict)
    for key in ("isin", "asset_name", "total", "document_urls"):
        assert key in result
